services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  js-backend:
    build:
      context: ./js-backend
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      python-multiline:
        condition: service_started

    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo:27017/graphocr
      PYTHON_SERVICE_URL: http://python-multiline:8123
    ports:
      - "5000:5000"

  python-multiline:
    build:
      context: ./python-multiline
    restart: unless-stopped
    environment:
      YOLO_MODEL_PATH: models/extract_header_model.pt
      TIFF_CHUNK_MODEL_PATH: best.pt
      USE_UNET_PIPELINE: "false"
    ports:
      - "8123:8123"

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      js-backend:
        condition: service_started
      python-multiline:
        condition: service_started
    ports:
      - "5173:3000"

volumes:
  mongo_data:
